### ISSUE TITLE
GLTFSCN: Difficult to select a single animation in multi-animation files

### ISSUE THREAD

**Issue by Utsira** [warrenm/GLTFKit#10]
Thanks for creating GLTFKit, it's awesome and I'm having a blast using it.

I'm using the 0.5.2 release.

I'm seeing an issue with animations in models downloaded from SketchFab. eg 

https://sketchfab.com/models/8993602ca91f4c499e690e5dae19f978

I've checked that the downloaded model passes the Khronos glTF validator, though it's possible that SketchFab might be doing something weird with the spec.

- I have a `GLTFAsset` with multiple animations, eg, this one has 3 animations, plus an "all": 
<img width="448" alt="image" src="https://user-images.githubusercontent.com/6677800/39922380-ca0e8362-5516-11e8-9d67-53fb1d817d70.png">

_Model with 4 animations viewed in Visual Studio Code with glTF Tools installed._

- I would like to be able to play these animations individually in SceneKit.
- Currently however, on conversion to an `SCNScene`, the nested structure of `GLTFAsset.animations.channels` gets flatmapped to a single array of `GLTFSCNAnimationTargetPair`
- Issue 1: In files with multiple animations, it is difficult to apply a single animation at once in GLTFSCN. To access eg Animation[2] I have to know the start channel and finish channel:

		let index = 2
		let start = index * 102
		let finish = start + 102
		for i in start..<finish {
			let pair = gltfScene.animations[i]
			pair.target.addAnimation(pair.animation, forKey: nil)
		}

- Proposed solution: `GLTFSCNAsset.animations` should preserve the same nested structure as `GLTFAsset.animations` and expose the animation's `name` to make it easier to distinguish the different animations.

- ~Issue 2: A single animation can be split into multiple channels (in this case 102), and each channel is mapped to a separate `CAAnimation` and applied with a separate `SCNAnimatable.addAnimation` call, and each call requires a unique string key. This makes managing the animations difficult: starting/ stopping/ merging animations would each require 102 separate calls with 102 unique string keys (this could be a weird way that SketchFab handles animations rather than an issue in GLTFKit). Would there be any way to concatenate the 102 CAAnimations into a single animation that can be started/ stopped/ merged with a single key? I'm not very knowledgable on animations, but I wonder whether `SCNAnimatable` would accept a `CAAnimationGroup` containing the various `CAAnimation`s? EDIT: `SCNAnimatable` does not like `CAAnimationGroup`: the code runs, but no animation is observable in the model.~

May I ask, do you welcome pull requests on this project?

**Comment by Utsira** [comment]
Exploring this particular model further, the 102 channels are divided between 34 nodes - 3 channels each, 1 each for translation, rotation, and scale. 

<img width="314" alt="image" src="https://user-images.githubusercontent.com/6677800/39927772-44321b2c-552b-11e8-9b55-a4ca78fef6e5.png">

As an aside, I highly recommend Visual Studio Code with the glTF Tools plugin for exploring/ verifying glTF assets.

Digging further, it seems that only the `rotation` channel contains content, the `translation` and `scale` channels consist of just 2 keyframes that contain the same values. So if you ignore these redundant animations, you only need 1 call for each of the 34 nodes. 

Here is a very crude check for redundancy (I skip any animation with fewer than 3 keyframes. I should really come up with a better check for redundancy, such as by comparing the keyValues. I don't get why the `CAKeyframeAnimation.values` are `NSRect`s though.)

		let index = 2
		let start = index * 102
		let finish = start + 102
		
		for i in start..<finish {
			let pair = gltfScene.animations[i]
			if let keyFrame = pair.animation as? CAKeyframeAnimation,
				let keyTimes = keyFrame.keyTimes,
				keyTimes.count > 2 {
					pair.target.addAnimation(pair.animation, forKey: "WALK")
			}
		}

I don't know enough to know whether this is an optimal way to organise a model, and I guess this is an issue with using assets found online, that they're not necessarily optimised for your own use scenario.

**Comment by warrenm** [comment]
Thanks for raising this issue. SceneKit animation support has long been a pain point, and I think we can make some progress here now. I've already made good progress on improving the API and getting playback to match more closely with Sketchfab. Currently working on a UI that allows selecting among animations.

**Comment by Utsira** [comment]
Every GLTF model I look at seems to have the pattern of 3 channels per node, 1 each for translation, scale, and rotation, even when in a lot of skeletal animation, only rotation is used. It seems like that would be a lot of overhead, having all those redundant animation channels. I wonder whether this is an area where the GLTF spec could be tightened up?

**Comment by warrenm** [comment]
I don't think it requires a spec change; the spec doesn't say you have to export animation channels that have no effect. Exporters just need to be smarter about what they emit.

**Comment by warrenm** [comment]
Check out 0134be94 and let me know if it addresses this issue. I added a basic UI to the SceneKit sample to allow selecting individual animations for playback, and to illustrated usage of the updated API.

**Comment by Utsira** [comment]
That's awesome, thanks! It also seems to address the timing offset issues with the "walk" animation.

**Comment by warrenm** [comment]
Nice. Yeah, it took a while to realize that I needed to use both the `beginTime` and `duration` properties of `CAAnimation` to get the correct behavior on start and on loop.

Closing now. Happy to reopen if issues still remain here.
