### ISSUE TITLE
Carthage Support?

### ISSUE THREAD

**Issue by sleroux** [warrenm/GLTFKit#4]
Hey there!

I'm able to pull down most of the frameworks alright using Carthage but the framework target for GLTFSCN is only for Mac. Looking at the source it seems that GLTFSCN supports iOS as well. Is there any plans to clean up the framework targets to work better with Carthage?

**Comment by warrenm** [comment]
Does 75d0f8fe work for you, and is it sufficient to address this? Do I need to create a release? I'm generally apathetic toward package managers, so I don't know what Carthage needs or expects.

**Comment by sleroux** [comment]
Yup that works! Carthage just compiles whatever framework targets are setup.

**Comment by warrenm** [comment]
Cool! Closing.
